[package]
name = "smeagol-wiki"
version = "0.1.2"
edition = "2021"
description = "A personal wiki webserver. Work in progress."
license = "MIT"
homepage = "https://github.com/AustinWise/smeagol/"
repository = "https://github.com/AustinWise/smeagol/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11"
clap = { version = "3.0.0", features = ["derive"] }
#hyper = { version = "0.14", features = ["server", "runtime", "http1"] }
log = "0.4"
pretty_env_logger = "0.4"
pulldown-cmark = { version = "0.9", default-features = false }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
#tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
toml = "0.5.8"
rocket = "0.5.0-rc.1"
