[package]
name = "rustwiki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11"
clap = { version = "3.0.0", features = ["derive"] }
hyper = { version = "0.14", features = ["server", "runtime", "http1"] }
log = "0.4"
pretty_env_logger = "0.4"
pulldown-cmark = { version = "0.9", default-features = false }
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
