[package]
name = "smeagol-wiki"
version = "0.4.1"
edition = "2021"
description = "A personal wiki webserver. Work in progress."
license = "MIT"
homepage = "https://github.com/AustinWise/smeagol/"
repository = "https://github.com/AustinWise/smeagol/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"

[build-dependencies]
ring = "0.16.20"

[dependencies]
askama = "0.11"
bitflags = "1.3.2"
clap = { version = "3.0.0", features = ["derive"] }
git2 = { version = "0.13", default-features = false }
log = "0.4"
once_cell = "1.9.0"
pretty_env_logger = "0.4"
pulldown-cmark = { version = "0.9", default-features = false }
rocket = "0.5.0-rc.1"
serde = { version = "1.0", features = ["derive"] }
strum = "0.23"
strum_macros = "0.23"
tantivy = "0.16.1"
thiserror = "1.0"
toml = "0.5.8"
