
name: ci
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  build-and-test:
    name: build-and-test
    runs-on: ${{ matrix.image }}
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        build: [linux-x64, macos-x64, win-x64-msvc]
        include:
        - build: linux-x64
          os: ubuntu
          image: ubuntu-20.04
          target: x86_64-unknown-linux-gnu
        - build: macos-x64
          os: macos
          image: macos-11
          target: x86_64-apple-darwin
        - build: win-x64-msvc
          os: windows
          image: windows-2022
          target: x86_64-pc-windows-msvc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
